
// PS3 buttons (pad data)
#define	CTRL_SELECT		(1<<0)
#define	CTRL_L3			(1<<1)
#define	CTRL_R3			(1<<2)
#define	CTRL_START		(1<<3)
#define	CTRL_UP			(1<<4)
#define	CTRL_RIGHT		(1<<5)
#define	CTRL_DOWN		(1<<6)
#define	CTRL_LEFT		(1<<7)
#define	CTRL_L2			(1<<8)
#define	CTRL_R2			(1<<9)
#define	CTRL_L1			(1<<10)
#define	CTRL_R1			(1<<11)
#define	CTRL_TRIANGLE	(1<<12)
#define	CTRL_CIRCLE		(1<<13)
#define	CTRL_CROSS		(1<<14)
#define	CTRL_SQUARE		(1<<15)